import Head from "next/head";

import { DarkProvider } from "@/context/DarkContext";

import Container from "./container";

import dotenv from "dotenv";

dotenv.config();

export default function Home() {
  return (
    <>
      <DarkProvider>
        <Head>
          <title>ChatGPT | OpenAI</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <main>
          <Container />
        </main>
      </DarkProvider>
    </>
  );
}
